spring.application.name=movieTicketBookingSystem

spring.datasource.url=jdbc:postgresql://localhost:5432/movie_ticket_db
spring.datasource.username=hgusain
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
